import React from 'react'

export default function Banner() {
  return (
    <div style={{margin:"96px 0px 0px 261px", width:"82%"}}>
        <h2>Lorem ipsum dolor sit amet consectetur adipisicing elit. At iusto commodi veritatis iste nostrum doloremque architecto culpa dolorum nesciunt quod necessitatibus, veniam explicabo nulla quaerat deserunt dicta exercitationem eaque hic delectus ut dolor aliquid qui dolore. Quaerat ad tempore veritatis numquam voluptatum optio blanditiis dolorem soluta ipsa, aliquam, vitae neque fugiat perferendis. Esse, quas. Amet eligendi, voluptatibus iure totam dolores officiis, quibusdam deleniti saepe modi mollitia nobis, molestiae nemo repudiandae facilis atque? Quae temporibus optio consequuntur repellat voluptatum doloremque. Vitae tenetur distinctio magni aut fugiat necessitatibus modi aperiam officia harum porro? Quisquam aut vel in est, voluptas pariatur minus? Distinctio autem saepe eos perspiciatis nulla quidem earum quaerat ducimus sunt praesentium et sit nostrum fuga, perferendis libero dolores nihil ex necessitatibus voluptates atque? Quas ullam odit eos libero labore perferendis quisquam aliquam? Aliquid dignissimos itaque natus aut dicta libero illo fuga animi voluptates dolore accusamus, officiis similique corrupti fugiat voluptatibus cum cupiditate beatae nemo illum error, labore adipisci numquam? Beatae ullam omnis molestiae tempore, maxime natus modi ad rem reprehenderit mollitia minus dolores in labore sit error laudantium voluptatibus quo odio vel itaque excepturi! Corrupti esse qui quia natus. Impedit, dolore aliquam reiciendis accusantium iste quia voluptates sint ad dolorum optio vitae, fugit deleniti labore repellendus eligendi unde voluptatibus eos facere rerum quidem consectetur beatae? Earum autem tempore cumque placeat eum nisi adipisci repellendus amet asperiores, inventore praesentium aut blanditiis eveniet ad est officiis totam! Dolores optio quas aliquid ex, unde iure corporis placeat ab, ratione est et? Inventore alias nihil illum labore. Temporibus perferendis assumenda reiciendis sapiente in voluptate culpa vero, voluptatum laudantium sed dignissimos eos odit necessitatibus magnam. Rerum omnis cum voluptatem voluptate, facilis tempore veniam ad magni assumenda aliquid ut fuga consectetur esse, deleniti iure est totam ea culpa. Blanditiis odit quidem sed. Quia sint sapiente esse!</h2>
    </div>
  )
}
